
CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "email" varchar(100),
  "password" varchar(100),
  "status" boolean DEFAULT false,
  "created_at" timestamp,
  "update_at" timestamp
);

CREATE TABLE "phone" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "phone" varchar(15),
  "user_id" integer,
  "created_at" timestamp,
  "update_at" timestamp
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "content" text,
  "user_id" integer,
  "created_at" timestamp,
  "update_at" timestamp
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(200) NOT NULL,
  "created_at" timestamp,
  "update_at" timestamp
);

CREATE TABLE "posts_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer,
  "post_id" integer,
  "created_at" timestamp,
  "update_at" timestamp
);

ALTER TABLE "phone" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "posts_categories" ADD FOREIGN KEY ("post_id") REFERENCES "posts" ("id");
ALTER TABLE "posts_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");


INSERT INTO users(name, email, password, status) VALUES('NTiendat', 'nguyentiendatg2003@gmail.com', 'Alo123456@', TRUE);
INSERT INTO phone(phone, user_id) VALUES('0869231211', 1);
INSERT INTO categories(name) VALUES('Kiến thức lập trình');
INSERT INTO posts(title, content, user_id) VALUES('Lộ trình học lập trình Fullstack', 'Hello các bạn', 1);
INSERT INTO posts_categories(category_id, post_id) VALUES(1, 1);
